[project]
name = "cache-proxy"
version = "0.1.0"
description = "CLI tool that starts a caching proxy server"
authors = [
    {name = "chineduCoded",email = "chinedujohn17@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard] (>=0.141.1,<0.142.0)",
    "redis[hiredis] (>=8.1.0,<9.0.0)",
    "prometheus-client (>=0.26.0,<0.27.0)"
]

[tool.poetry]
packages = [
    { include = "app" }
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest-anyio (>=0.0.0,<0.0.1)",
    "ruff (>=0.16.8,<0.17.0)",
    "mypy (>=2.3.1,<3.0.0)",
    "pytest (>=9.1.1,<10.0.0)"
]
