[tool.poetry]
name = "caching-proxy"
version = "0.1.0"
description = "CLI tool that starts a caching proxy server, it will forward requests to the actual server and cache the responses."
authors = ["chineduCoded <chinedujohn17@gmail.com>"]
readme = "README.md"
packages = [
    { include = "app", from = "." }
]

[tool.poetry.scripts]
caching-proxy = "app.cli:cli"

[tool.poetry.dependencies]
python = "^3.13"
fastapi = {extras = ["standard"], version = "^0.141.1"}
httpx = "^0.28.1"
httpx2 = "^2.13.0"
redis = {extras = ["hiredis"], version = "^8.1.0"}
booktype = "^1.5"
pydantic-settings = "^2.15.0"
prometheus-client = "^0.26.0"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
pytest-anyio = "^0.0.0"
mypy = "^2.3.1"
ruff = "^0.16.8"

[tool.mypy]
python_version = "3.13"
strict = true
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
